services:
###########################
# Setup the PHP container
###########################
    linux_asm:
        container_name: ${NAME_PROJECT}_asm
        restart: always
        build: 
            context: ./.docker/images/linux_asm/
            args:
                - VALUE_GCC_VERSION=${VALUE_GCC_VERSION}
        tty: true
        stdin_open: true
        volumes:
            - ./project:/home/project:rw
